### PR TITLE
Exposes simple authentication method option

### PR DESCRIPTION
**Pull request by feu-de-bois**
## Description
Exposes simple AUTHENTICATE_USER option accepting a method that return true or false and allows the consumer to define the authentication procedure.
Return basic 403 response if AUTHENTICATE_USER method exists and returns False.
Updates message handler call and base message handlers to accept the request object.
Updates flake8 and pycodestyle to allow for longer lines.
Updates .editorconfig to allow longer lines.
Fixes decoration of logging_view.

### CODE REVIEW

**Comment by nalch** [comment]
I don't think, that the authentication should be part of the package. That's better handled in the client's project.

Maybe with something like [django-decorator-include](https://pypi.org/project/django-decorator-include/).
`url(r'^logs', decorator_include(login_required, 'logging_endpoint.urls'))`

I can be persuaded though.

**Comment by feu-de-bois** [comment]
Agreed that is a much more elegant way to handle this.  It would be nice if this was functionality rolled into django or DRF itself.  It does not seem to be however.  This then requires another dependency that we would need to vendor.   Not sure which is the worse evil :sweat_smile:

**Comment by lonetwin** [comment]
I agree with @nalch -- authentication doesn't belong here.

Also, unless I am not understanding something, we might not need a third-party dependency if we configure the url with the plain regular [login_required](https://docs.djangoproject.com/en/3.0/topics/auth/default/#django.contrib.auth.decorators.login_required) decorator ? Presumably one might be able to configure the endpoint in the application using `django-logging-endpoint` like so:
```python
from django.contrib.auth.decorators import login_required
import logging_endpoint
...
url(r'^logs', login_required(logging_endpoint.views.logging_view))
...
```

[Quick](https://www.fullstackpython.com/django-contrib-auth-decorators-login-required-examples.html) [searches](https://github.com/GetStream/django_twitter/blob/master/pytutorial/urls.py#L15-L23) seem to suggest this is a valid pattern (although those were for class based views, I don't see why it wouldn't still work).

**Comment by nalch** [comment]
Maybe I could interest you in an easy to maintain middleware for the actual project (untested, but should be possible like this):
```
settings:
LOGIN_REQUIRED_URLS = ['log-endpoint']

def login_required_middleware(get_response):
    def middleware(request):
    	current_url = request.resolver_match.url_name
    	if current_url in settings.LOGIN_REQUIRED_URLS:
    		if not hasattr(request, 'user') or not request.user.is_authenticated:
    			raise PermissionDenied()

        return get_response(request)

    return middleware
```

**Comment by feu-de-bois** [comment]
FWIW the decorator pattern did work and I can utilize all of the auth structure of DRF.  This approach seems fine to me for now.
```
from rest_framework.decorators import api_view
from logging_endpoint.views import logging_view

api_view = api_view(['POST'])
url(r'^api/logs$', api_view(logging_view))
```

**Pull request closed without merging**
